import { defineConfig } from 'eslint/config'; // eslint-disable-line import/no-unresolved
import globals from 'globals';
import importPlugin from 'eslint-plugin-import';
import js from '@eslint/js';
import reactPlugin from 'eslint-plugin-react';
import stylistic from '@stylistic/eslint-plugin';

export default defineConfig([
	{
		ignores: ['build/**/*', 'dist/**/*', 'example/build/**/*', 'public/assets/js/*.min.js', 'vendor/**/*'],
	},
	{
		files: ['**/*.test.js'],
		languageOptions: {
			globals: {
				...globals.jest,
				before: 'readonly',
				context: 'readonly',
				cy: 'readonly',
				Cypress: 'readonly',
			},
		},
	},
	{
		files: ['**/*.{js,jsx}'],
		extends: [
			js.configs.recommended,
			importPlugin.flatConfigs.recommended,
			reactPlugin.configs.flat.recommended,
			reactPlugin.configs.flat['jsx-runtime'],
		],
		languageOptions: {
			ecmaVersion: 'latest',
			globals: globals.browser,
		},
		settings: {
			react: {
				jsxRuntime: 'automatic',
				version: 'detect',
			},
		},
		plugins: {
			'@stylistic': stylistic,
		},
		rules: {
			...stylistic.configs.customize({
				indent: 'tab',
				semi: true,
			}).rules,
			'@stylistic/array-bracket-newline': ['error', 'consistent'],
			'@stylistic/arrow-parens': ['error', 'always'],
			'@stylistic/brace-style': ['error', '1tbs'],
			'@stylistic/comma-dangle': ['error', {
				arrays: 'always-multiline',
				objects: 'always-multiline',
				imports: 'always-multiline',
				exports: 'always-multiline',
				functions: 'never',
			}],
			'@stylistic/curly-newline': ['error', { minElements: 1 }],
			'@stylistic/function-call-argument-newline': ['error', 'consistent'],
			'@stylistic/function-call-spacing': ['error', 'never'],
			'@stylistic/function-paren-newline': ['error', 'consistent'],
			'@stylistic/jsx-newline': 0,
			'@stylistic/jsx-pascal-case': ['error'],
			'@stylistic/jsx-self-closing-comp': ['error'],
			'@stylistic/jsx-sort-props': 0, // TODO.
			'@stylistic/linebreak-style': ['error', 'unix'],
			'@stylistic/max-len': ['error', 150],
			'@stylistic/multiline-ternary': 0,
			'@stylistic/newline-per-chained-call': 0, // TODO.
			'@stylistic/no-confusing-arrow': ['error'],
			'@stylistic/no-extra-semi': ['error'],
			'@stylistic/no-multi-spaces': ['error'],
			'@stylistic/object-curly-newline': [
				'error',
				{
					multiline: true,
					consistent: true,
				},
			],
			'@stylistic/one-var-declaration-per-line': ['error'],
			'@stylistic/padding-line-between-statements': ['error'],
			'@stylistic/quotes': ['error', 'single', { avoidEscape: true }],
			'@stylistic/quote-props': ['error', 'as-needed'],
			'@stylistic/semi-style': ['error', 'last'],
			'@stylistic/switch-colon-spacing': ['error'],
			'array-callback-return': ['error'],
			'no-await-in-loop': ['error'],
			'no-constructor-return': ['error'],
			'no-duplicate-imports': ['error'],
			'no-inner-declarations': ['error'],
			'no-promise-executor-return': ['error'],
			'no-self-compare': ['error'],
			'no-template-curly-in-string': ['error'],
			'no-unassigned-vars': ['error'],
			'no-unmodified-loop-condition': ['error'],
			'no-unreachable-loop': ['error'],
			'no-useless-assignment': ['error'],
			'arrow-body-style': ['error'],
			'block-scoped-var': ['error'],
			camelcase: ['error', { properties: 'never' }],
			'capitalized-comments': ['error', 'always', { ignoreConsecutiveComments: true }],
			complexity: ['error'],
			'consistent-return': ['error'],
			'consistent-this': ['error'],
			curly: ['error'],
			'default-param-last': ['error'],
			'dot-notation': ['error'],
			eqeqeq: ['error'],
			'import/extensions': ['error', 'ignorePackages'],
			'import/first': 'error',
			'import/newline-after-import': 'error',
			'import/no-extraneous-dependencies': 'error',
			'import/no-absolute-path': 'error',
			'import/no-cycle': 'error',
			'import/no-self-import': 'error',
			'import/no-useless-path-segments': 'error',
			'import/no-deprecated': 'error',
			'max-classes-per-file': ['error'],
			'max-depth': ['warn'],
			'max-nested-callbacks': ['error'],
			'new-cap': ['error'],
			'no-alert': ['error'],
			'no-array-constructor': ['error'],
			'no-bitwise': ['error'],
			'no-console': ['error'],
			'no-else-return': ['error'],
			'no-eval': ['error'],
			'no-extend-native': ['error'],
			'no-implicit-coercion': ['error'],
			'no-implicit-globals': ['error'],
			'no-implied-eval': ['error'],
			'no-invalid-this': ['error'],
			'no-loop-func': ['error'],
			'no-multi-assign': ['error'],
			'no-negated-condition': ['error'],
			'no-nested-ternary': ['error'],
			'no-new-wrappers': ['error'],
			'no-new': ['error'],
			'no-object-constructor': ['error'],
			'no-plusplus': ['error'],
			'no-return-assign': ['error'],
			'no-script-url': ['error'],
			'no-sequences': ['error'],
			'no-shadow': ['error'],
			'no-throw-literal': ['error'],
			'no-unneeded-ternary': ['error'],
			'no-unused-expressions': ['error'],
			'no-useless-computed-key': ['error'],
			'no-useless-concat': ['error'],
			'no-useless-rename': ['error'],
			'no-useless-return': ['error'],
			'no-var': ['error'],
			'no-warning-comments': 0, // TODO.
			'object-shorthand': ['error'],
			'one-var': ['error', 'never'],
			'operator-assignment': ['error'],
			'prefer-arrow-callback': ['error'],
			'prefer-const': ['error'],
			'prefer-object-has-own': ['error'],
			'prefer-object-spread': ['error'],
			'prefer-promise-reject-errors': ['error'],
			'prefer-regex-literals': ['error'],
			'prefer-template': ['error'],
			'preserve-caught-error': ['error'],
			radix: ['error'],
			'require-await': ['error'],

			'react/boolean-prop-naming': 'error',
			'react/button-has-type': 'error',
			'react/checked-requires-onchange-or-readonly': 'error',
			'react/default-props-match-prop-types': 'error',
			'react/destructuring-assignment': 'error',
			'react/forbid-dom-props': 'error',
			'react/forbid-elements': 'error',
			'react/forbid-foreign-prop-types': 'error',
			// 'react/forbid-prop-types': 'error', // TODO.
			'react/forward-ref-uses-ref': 'error',
			'react/function-component-definition': 'error',
			'react/hook-use-state': 'error',
			'react/iframe-missing-sandbox': 'error',
			'react/jsx-boolean-value': 'error',
			'react/jsx-closing-bracket-location': 'error',
			'react/jsx-closing-tag-location': 'error',
			'react/jsx-curly-brace-presence': 'error',
			'react/jsx-curly-newline': 'error',
			'react/jsx-curly-spacing': 'error',
			'react/jsx-equals-spacing': 'error',
			'react/jsx-filename-extension': 'error',
			'react/jsx-first-prop-new-line': 'error',
			'react/jsx-fragments': 'error',
			'react/jsx-handler-names': 'error',
			// 'react/jsx-no-bind': 'error', // TODO.
			'react/jsx-no-constructed-context-values': 'error',
			// 'react/jsx-no-leaked-render': 'error', // TODO.
			'react/jsx-no-script-url': 'error',
			'react/jsx-no-useless-fragment': 'error',
			'react/jsx-pascal-case': 'error',
			'react/jsx-props-no-multi-spaces': 'error',
			'react/jsx-props-no-spread-multi': 'error',
			'react/jsx-tag-spacing': 'error',
			'react/jsx-wrap-multilines': 'error',
			'react/no-access-state-in-setstate': 'error',
			'react/no-adjacent-inline-elements': 'error',
			'react/no-array-index-key': 'error',
			'react/no-arrow-function-lifecycle': 'error',
			'react/no-danger': 'error',
			'react/no-did-mount-set-state': 'error',
			'react/no-did-update-set-state': 'error',
			'react/no-invalid-html-attribute': 'error',
			'react/no-multi-comp': 'error',
			'react/no-namespace': 'error',
			// 'react/no-object-type-as-default-prop': 'error', // TODO.
			'react/no-redundant-should-component-update': 'error',
			'react/no-set-state': 'error',
			'react/no-this-in-sfc': 'error',
			'react/no-typos': 'error',
			// 'react/no-unstable-nested-components': 'error', // TODO.
			'react/no-unused-class-component-methods': 'error',
			'react/no-unused-prop-types': 'error',
			'react/no-unused-state': 'error',
			'react/no-will-update-set-state': 'error',
			'react/prefer-es6-class': 'error',
			'react/prefer-exact-props': 'error',
			'react/prefer-read-only-props': 'error',
			'react/prefer-stateless-function': 'error',
			// 'react/require-default-props': 'error', // TODO.
			'react/require-optimization': 'error',
			'react/self-closing-comp': 'error',
			'react/sort-comp': 'error',
			'react/sort-default-props': 'error',
			'react/sort-prop-types': 'error',
			'react/state-in-constructor': 'error',
			'react/static-property-placement': 'error',
			'react/style-prop-object': 'error',
			'react/void-dom-elements-no-children': 'error',
		},
	},
	{
		files: ['*.config.js'],
		languageOptions: {
			sourceType: 'module',
			globals: globals.node,
		},
	},
]);
